### ISSUE TITLE
[Feat] $? 구현

### ISSUE THREAD

**Issue by LWJ0513** [LWJ0513/minishell#16]
## Description
echo $? 를 위해 각 함수를 실행시킨 결과를 변수에 저장한다.

## Todo
- [x] main 에서 변수에 값 저장
- [x] 구조체에 변수 선언
- [x] echo 에서 $? 출력 구현
