### ISSUE TITLE
[Feat] pipe를 기준으로 파싱

### ISSUE THREAD

**Issue by LWJ0513** [LWJ0513/minishell#23]
## Description
 | 구분자가 들어올 경우를 대비해 명령어들을 나눠 연결리스트에 저장한다.

## Todo
- [x] pipe 기준으로 split
- [x] 명령어들을 연결리스트에 저장
- [x] pipe 예외처리 

### 예외처리
- [x] ls |  -> readline    -> 개행 있는 건 add_history, 없는 건 파싱
- [x] pipe> 출력
- [x] ls || 
- [x] ls | |
- [x] 공백에 대한 split ---- 공백을 넣으면 cnt_cmd 가 증가  ex) `ls | |` 일 경우 cnt_cmd  = 2   
- [x] | ls
- [x] | | d

**Comment by LWJ0513** [comment]
끝
