### ISSUE TITLE
[Feat] 환경변수 파싱

### ISSUE THREAD

**Issue by LWJ0513** [LWJ0513/minishell#37]
## Description
envp 로 받아온 내용 중 PATH 를 이용해 들어온 명령어에 대한 위치를 찾아내어 문자열을 합쳐서 반환해준다.

## Todo
- [x] PATH 내용을 콜론을 기준으로 split
- [x] 명령어 전체를 확인하면서 경로와 연결해 실행파일이 있는지 확인한다.
   - [x] 찾을 필요가 없는 명령어에 대한 예외처리
   - [x] 없으면 널을 리턴한다.
- [x] 찾게 되면 명령어 문자열을 경로 문자열로 변경해 저장한다.
- [x] 헤더에 valid_path 함수 선언, makeflie valid_path.c 추가

## 생각할 점
export나 unset을 사용해 PATH 가 수정될 경우 새로 불러 초기화해야한다.
매번 split을 하기엔 너무 비효율적이므로 path가 삭제되거나 새로 설정되면 위에서 정의한 함수를 불러 재설정 해야 한다.
*** 재설정하기 전에 이전의 이차원 포인터 free
