### ISSUE TITLE
[Feat] pwd 기능 구현

### ISSUE THREAD

**Issue by LWJ0513** [LWJ0513/minishell#8]
## Description
pwd 를 입력하면 bash랑 똑같이 작동하게 구현한다

## Todo
- [x] pwd 함수 구현
- [x] main 함수에 연결
- [x] 헤더에 함수 선언부 추가
- [x] Makefile에 소스파일 추가
